name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-21"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTUzOTFmNDktMjFhYy00NTE0LWIzMDktYWFmMjlkZmRiMDkzIiwidGVuYW50X2lkIjoiYmNiODM3MTg4MjY2ZDVmMzA0NWI5MDYxYjdlYjExZTFlMTliYTNjYmJmOTU1ZDdhMDgyMWZiZTdmOTQ2MTM5YiIsImludGVybmFsX3NlY3JldCI6ImZjNDgwMDcxLTlhMjgtNGYwMi04ZTUwLWVmYzBmMTg3YjdiZSJ9.DJxvT6cy4DsklCpNQ5HXEjKc2O4vM8oEZUmbrelq6lk"
DIRECT_URL="postgresql://demo1_owner:HtK27BCGwRZe@ep-small-dust-a514s86o.us-east-2.aws.neon.tech/demo1?sslmode=require"
JWT_SECRET = "leosecretkey"
